---
title: "Covid-19 World Data in Graphs"
output: html_document
---


### Dataset was pulled from John Hopkins University

```{r dataset, include=FALSE}
confirmedglobal <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
str(confirmedglobal) # check most recent date

deathsglobal <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

recoveredglobal <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")

```


```{r dplyr, tidyr, include=FALSE}
library(tidyr)
library(dplyr)

confirmed <- confirmedglobal %>% gather(key = "date",value = "confirmed", -c(Country.Region, Province.State, Lat, Long))%>% 
  group_by(Country.Region, date) %>% 
  summarize(confirmed = sum(confirmed))

deaths <- deathsglobal %>% gather(key = "date", value = "deaths",
                                  -c(Country.Region,Province.State, Lat, Long)) %>% 
  group_by(Country.Region, date) %>% 
  summarize(deaths=sum(deaths))

recovered <- recoveredglobal %>% gather(key = "date", value = "recovered",
                                        -c(Country.Region,Province.State,Lat,Long)) %>% 
  group_by(Country.Region, date) %>% 
  summarize(recovered = sum(recovered))
summary(confirmed)

#Final data : Combine all three
country <- full_join(confirmed,deaths) %>% full_join(recovered)
# Date variable
# Fix date variable and convert from character to date
str(country) # check date character
country$date <- country$date %>% sub("X", "", .) %>% as.Date("%m.%d.%y")
str(country) # check date Date

#Create new variable : number of days
country <- country %>% group_by(Country.Region) %>% 
  mutate(cumconfirmed = cumsum(confirmed), days = date - first(date) + 1)

#Aggregate at world level
world <- country %>% group_by(date) %>% 
  summarize(confirmed= sum(confirmed),
            cumconfirmed=sum(cumconfirmed),
            deaths=sum(deaths),
            recovered=sum(recovered))%>% 
  mutate(days = date-first(date)+1)

```


```{r australia, include=FALSE}
#Extract specific country : Italy
australia <- country %>% filter(Country.Region == "Australia")
```


```{r summary statistics, include=FALSE}
summary(country)
by(country$confirmed,country$Country.Region, summary)
by(country$cumconfirmed, country$Country.Region, summary)
by(country$deaths, country$Country.Region, summary)
by(country$recovered, country$Country.Region, summary)
summary(world)
```

## GRAPHS

### Barchart of cases over time :

```{r ggplot2, include=FALSE}
library(ggplot2)
```


```{r world confirmed, echo=FALSE}
#World confirmed
ggplot(world, aes(x = date, y= confirmed)) +
  geom_bar(stat="identity",
           width = 0.1)+
  theme_classic()+
  labs(title = "Covid-19 Global Confirmed Cases", x = "Date", y= "Daily confirmed cases")+
  theme(plot.title = element_text(hjust = 0.5))

plot(world)
```


```{r world, include=FALSE}
# World confirmed, deaths, recovered
str(world)
world %>% gather("Type","Cases",-c(date,days)) %>% 
  ggplot(aes(x = date, y = Cases, colour = Type))+
           geom_bar(stat = "identity", width = 0.2, fill ="white")+
           theme_classic()+
           labs(title = "Covid-19 Global Cases", x = "Date", y = "Daily cases")+
           theme(plot.title = element_text(hjust = 0.5))
```

```{r australia_confirmed, echo=FALSE}
# Australia confirmed
ggplot(australia, aes(x = date, y = confirmed)) + geom_bar(stat = "identity", width = 0.1)+
  theme_classic()+
  labs(title = "Covid-19 Confirmed Cases in Australia", x= "Date", y= "Daily confrmed cases")+
  theme(plot.title = element_text(hjust = 0.5))
```

### Line graph of cases over time

```{r world_confirmed, echo=FALSE}
# World confirmed
ggplot(world, aes(x=days, y=confirmed)) + geom_line() +
  theme_classic() +
  labs(title = "Covid-19 Global Confirmed Cases", x= "Days", y= "Daily confirmed cases") +
  theme(plot.title = element_text(hjust = 0.5))
```

### World confirmed with counts in log10 scale
```{r world_confirmedLOG, echo=FALSE}
ggplot(world, aes(x=days, y=confirmed)) + geom_line() +
  theme_classic() +
  labs(title = "Covid-19 Global Confirmed Cases", x= "Days", y= "Daily confirmed cases  (log scale)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans="log10")

```


### World confirmed, deaths and recovered
```{r worldtwo, echo=FALSE}
# World confirmed, deaths and recovered
#str(world)
world %>% gather("Type", "Cases", -c(date, days)) %>%
ggplot(aes(x=days, y=Cases, colour=Type)) + geom_line() +
  theme_classic() +
  labs(title = "Covid-19 Global Cases", x= "Days", y= "Daily cases") +
  theme(plot.title = element_text(hjust = 0.5))
```


### Confirmed by country for select countries with counts in log10 scale
```{r country_selection1, include=FALSE, echo=FALSE}
countryselection <- country %>% filter(Country.Region==c("US", "Italy", "China", "France", "United Kingdom", "Germany"))
```

```{r country_selection, echo=FALSE}
ggplot(countryselection, aes(x=days, y=confirmed, colour=Country.Region)) + geom_line(size=1) +
  theme_classic() +
  labs(title = "Covid-19 Confirmed Cases by Country", x= "Days", y= "Daily confirmed cases (log scale)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans="log10")
```

### Matrix of line graphs of confirmed, deaths and recovered for select countries in log10 scale
```{r countryselection3, echo=FALSE, include=FALSE}
str(countryselection)
```

```{r facet, echo=FALSE,}

countryselection %>% gather("Type", "Cases", -c(date, days, Country.Region)) %>%
ggplot(aes(x=days, y=Cases, colour=Country.Region)) + geom_line(size=1) +
  theme_classic() +
  labs(title = "Covid-19 Cases by Country", x= "Days", y= "Daily cases (log scale)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans="log10") +
  facet_grid(rows=vars(Type))
```

